# Generated by Django 5.0.7 on 2024-08-01 00:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appname', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='produto',
            name='situprod',
        ),
        migrations.RemoveField(
            model_name='venda',
            name='descvend',
        ),
        migrations.AddField(
            model_name='produto',
            name='qntdprod',
            field=models.IntegerField(default=1000),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='venda',
            name='codivend',
            field=models.CharField(default='2e409fc699', max_length=10, unique=True),
        ),
    ]
