# Generated by Django 5.0.7 on 2024-08-01 00:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appname', '0002_remove_produto_situprod_remove_venda_descvend_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='venda',
            name='codivend',
            field=models.CharField(default='b6b171752e', max_length=10, unique=True),
        ),
    ]
