# Generated by Django 5.0.7 on 2024-08-01 00:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appname', '0003_alter_venda_codivend'),
    ]

    operations = [
        migrations.AlterField(
            model_name='venda',
            name='codivend',
            field=models.CharField(default='d312e7935a', max_length=10, unique=True),
        ),
    ]
