# Generated by Django 5.0.7 on 2024-08-01 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appname', '0007_alter_venda_codivend'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='cidcli',
            field=models.CharField(max_length=50, verbose_name='Cidade'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='cnpjcli',
            field=models.CharField(max_length=20, verbose_name='CNPJ'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='codcli',
            field=models.CharField(max_length=10, verbose_name='Código Cliente'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='datacli',
            field=models.DateField(verbose_name='Data'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='estcli',
            field=models.CharField(max_length=100, verbose_name='Estado'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='fonecli',
            field=models.CharField(max_length=20, verbose_name='Fone Cliente'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='nomecli',
            field=models.CharField(max_length=100, verbose_name='Nome do Cliente'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='razasoccli',
            field=models.CharField(max_length=100, verbose_name='Razão Social'),
        ),
        migrations.AlterField(
            model_name='venda',
            name='codivend',
            field=models.CharField(default='a0da056f72', max_length=10, unique=True),
        ),
    ]
